/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/host`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/join`; params?: Router.UnknownInputParams; } | { pathname: `/oldIndex`; params?: Router.UnknownInputParams; } | { pathname: `/room`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Place`; params?: Router.UnknownInputParams; } | { pathname: `/globalStyles/globalStyles`; params?: Router.UnknownInputParams; } | { pathname: `/globalStyles/theme`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/host`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/join`; params?: Router.UnknownOutputParams; } | { pathname: `/oldIndex`; params?: Router.UnknownOutputParams; } | { pathname: `/room`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Place`; params?: Router.UnknownOutputParams; } | { pathname: `/globalStyles/globalStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/globalStyles/theme`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/host${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/join${`?${string}` | `#${string}` | ''}` | `/oldIndex${`?${string}` | `#${string}` | ''}` | `/room${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Place${`?${string}` | `#${string}` | ''}` | `/globalStyles/globalStyles${`?${string}` | `#${string}` | ''}` | `/globalStyles/theme${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/host`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/join`; params?: Router.UnknownInputParams; } | { pathname: `/oldIndex`; params?: Router.UnknownInputParams; } | { pathname: `/room`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Place`; params?: Router.UnknownInputParams; } | { pathname: `/globalStyles/globalStyles`; params?: Router.UnknownInputParams; } | { pathname: `/globalStyles/theme`; params?: Router.UnknownInputParams; };
    }
  }
}
